AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Resources for options project deploy


Parameters:

  ApiGatewayName:
    Type: String
    Default: options

  ApiGatewayStageName:
    Type: String
    Default: v1

  LambdaRole:
    Type: String
    Default: arn:aws:iam::182960656850:role/lambda-role
    Description: Role for lambda permission on AWS resources

  ApiRole:
    Type: String
    Default: arn:aws:iam::182960656850:role/api-role


Resources:

  StrategiesECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: underlying-strategies

  StrategiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TB_UNDERLYING_STRATEGIES
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: username-index
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  StrategiesAPI:
    Type: AWS::ApiGatewayV2::Api
    DependsOn:
      - APIHealthLambda
    Properties:
      Name: strategies-api
      Description: API to provide crude interface strategies
      ProtocolType: HTTP
      Target: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${APIHealthLambda.Arn}/invocations
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["*"]
        AllowHeaders: ["Authorization"]
        ExposeHeaders: ["Access-Control-Allow-Origin"]

  CreateRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - CreateIntegration
    Properties:
      ApiId: !Ref StrategiesAPI
      RouteKey: "POST /create"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref CreateIntegration

  CreateIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref StrategiesAPI
      Description: Integration for create strategy to lambda invoke
      CredentialsArn: !Ref ApiRole
      ConnectionType: INTERNET
      PayloadFormatVersion: "2.0"
      PassthroughBehavior: WHEN_NO_MATCH
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateLambda.Arn}/invocations

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn:
      - CreateRoute
    Properties:
      ApiId: !Ref StrategiesAPI
      StageName: v1
      Description: API deployment stage
      AutoDeploy: True

  CreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: STRATEGIES-API-CREATE
      Description: Create strategy
      PackageType: Image
      Role: !Ref LambdaRole
      Timeout: 30
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          STRATEGY_TABLE: !Ref StrategiesTable
    Metadata:
      DockerTag: strategies-api-create
      DockerContext: functions/api/create
      Dockerfile: Dockerfile

  APIHealthLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: STRATEGIES-API-HEALTH
      Description: Health check Strategies API
      Runtime: python3.8
      Handler: app.app.lambda_handler
      CodeUri: functions/api/health
      Role: !Ref LambdaRole
