AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Resources for options service


Parameters:

  ApiGatewayName:
    Type: String
    Default: options

  ApiGatewayStageName:
    Type: String
    Default: v1

  LambdaRole:
    Type: String
    Default: arn:aws:iam::182960656850:role/lambda-role
    Description: Role for lambda permission on AWS resources

  ApiRole:
    Type: String
    Default: arn:aws:iam::182960656850:role/api-role


Globals:
  Function:
    Runtime: python3.9


Resources:

  OptionsECR:
    Type: AWS:ECR:Repository
    Properties:
      RepositoryName: underlying-options

  OptionsDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: underlying-options-data
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OptionsSeriesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: underlying-options-series
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
