AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: General infrastructure resources for undelying project


Parameters:

  ApiRole:
    Type: String
    Default: arn:aws:iam::182960656850:role/api-role


Resources:

  OpenSearchUnderlying:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: underlying
      EngineVersion: Elasticsearch_7.7
      ClusterConfig:
        InstanceCount: 2
        ZoneAwarenessEnabled: true
        InstanceType: t3.small.search
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS: '*'
            Action:
              - 'es:*'
            Resource: 'arn:aws:es:us-east-1:182960656850:domain/underlying/*'
            Condition:
              IpAddress:
                aws:SourceIp:
                  - '179.108.21.132'
          - Effect: 'Allow'
            Principal:
              AWS: '*'
            Action:
              - 'es:*'
            Resource: 'arn:aws:es:us-east-1:182960656850:domain/underlying/*'
