name: Deploy Strategy CloudFormation Stacks

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

jobs:
  strategies-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Install SAM dependencies
        uses: aws-actions/setup-sam@v1

      - name: Validate Strategies template
        id: validate-template
        run: sam validate -t $template
        env:
          template: "strategies/template.yaml"

      - name: Build Strategies Service AWS
        id: strategies-build
        run: sam build --template-file $template
        env:
          template: "strategies/template.yaml"

      - name: Deploy Strategies Service AWS
        id: strategies-deploy
        run: sam deploy --no-fail-on-empty-changeset --s3-bucket $bucket --s3-prefix $prefix --stack-name $stack --capabilities $capabilities --region ${{ github.event.inputs.region }} --image-repository $ecr
        env:
          bucket: "underlying-deployments"
          prefix: "STRATEGIES"
          stack: "STRATEGIES"
          capabilities: "CAPABILITY_IAM"
          template: "strategies/template.yaml"
#          ecr: "182960656850.dkr.ecr.us-east-1.amazonaws.com/underlying-strategies"